services:
  mysql80:
    container_name: mysql80
    image: mysql/mysql-server:8.0
    ports:
      - "3312:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=apiuser
      - MYSQL_PASSWORD=ap1u5er
      - MYSQL_DATABASE=library
    volumes:
      - ./init-files:/docker-entrypoint-initdb.d